# -*- coding: utf-8 -*-
"""Risk-Sentinel v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6Hm89jse9lKr1sN9fEFAMCXhVlCTCHa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

class RiskSentinel:
    def __init__(self):
        self.threshold_psi = 0.25

    def calculate_psi(self, expected, actual, bins=10):
        # Aseguramos que los datos sean arrays de numpy
        expected = np.array(expected)
        actual = np.array(actual)

        breakpoints = np.percentile(expected, np.linspace(0, 100, bins + 1))
        breakpoints[0], breakpoints[-1] = -np.inf, np.inf

        expected_per = np.histogram(expected, bins=breakpoints)[0] / len(expected)
        actual_per = np.histogram(actual, bins=breakpoints)[0] / len(actual)

        expected_per = np.where(expected_per == 0, 0.0001, expected_per)
        actual_per = np.where(actual_per == 0, 0.0001, actual_per)

        psi_value = np.sum((actual_per - expected_per) * np.log(actual_per / expected_per))
        return psi_value

    def plot_vintage_analysis(self, df_prod):
        """Genera la gráfica de Vintages de forma independiente."""
        plt.figure(figsize=(10, 5))
        for mes in sorted(df_prod['MES_ORIGINACION'].unique()):
            subset = df_prod[df_prod['MES_ORIGINACION'] == mes]
            base_mora = subset['DEFAULT_REAL'].mean()
            meses_vida = np.arange(1, 7)
            # Simulación de curva de maduración
            curva = base_mora * (1 / (1 + np.exp(-(meses_vida - 2))))

            color = 'red' if mes == 3 else None
            plt.plot(meses_vida, curva, marker='o', label=f'Cosecha Mes {mes}', color=color)

        plt.title('Vintages: Tasa de Default Acumulada', fontsize=12, fontweight='bold')
        plt.xlabel('Meses tras el otorgamiento')
        plt.ylabel('% de Mora Real')
        plt.legend()
        plt.show()

    def run_audit(self, df_ref, df_prod):
        """Realiza los cálculos sin disparar gráficas automáticamente."""
        # Comparar ingreso de referencia vs el ingreso de la cosecha más reciente (Marzo)
        actual_data = df_prod[df_prod['MES_ORIGINACION'] == 3]['INGRESO']

        psi_val = self.calculate_psi(df_ref['INGRESO_REAL'], actual_data)

        print(f"🔍 Auditoría Finalizada.")
        print(f"📊 PSI Detectado: {psi_val:.4f}")

        return psi_val

# ==============================================================================
# EJECUCIÓN CORREGIDA
# ==============================================================================

# 1. Datos de Referencia (Entrenamiento)
df_ref = pd.DataFrame({
    'INGRESO_REAL': np.random.lognormal(mean=np.log(18000), sigma=0.5, size=5000),
    'TARGET': np.random.binomial(1, 0.08, 5000)
})

# 2. Datos de Producción (Q1 2026)
prod_list = []
for mes in [1, 2, 3]:
    ingreso_med = 13500 if mes == 3 else 18000
    mora = 0.16 if mes == 3 else 0.05
    df_mes = pd.DataFrame({
        'MES_ORIGINACION': mes,
        'INGRESO': np.random.normal(ingreso_med, 4000, 1000),
        'DEFAULT_REAL': np.random.binomial(1, mora, 1000)
    })
    prod_list.append(df_mes)

df_prod = pd.concat(prod_list)

# 3. Ejecución controlada
sentinel = RiskSentinel()

# Paso A: Solo cálculos
psi_res = sentinel.run_audit(df_ref, df_prod)

# Paso B: Solo gráfica (Llamada explícita para evitar duplicidad)
sentinel.plot_vintage_analysis(df_prod)